# customers Feature Engineering

## Objective

This notebook creates business-oriented features from the cleaned `customers` dataset.

In [1]:
import pandas as pd
import numpy as np

customers = pd.read_csv(
    "../../03_Python_ETL/Output/customers_clean.csv"
)

In [23]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_city_state,customer_order_count
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,"franca, SP",1
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,"sao bernardo do campo, SP",1
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,"sao paulo, SP",1
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,"mogi das cruzes, SP",1
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,"campinas, SP",1

### Feature 1: customer_city_state
**Business Purpose**

Creates a combined geographic identifier (city + state) that is much more useful for reporting than separate columns. It simplifies grouping, filtering, and visualization in SQL and Power BI.

In [2]:
customers["customer_city_state"] = (
    customers["customer_city"] + ", " +
    customers["customer_state"]
)

In [3]:
# Validation
customers[
    [
        "customer_city",
        "customer_state",
        "customer_city_state"
    ]
].head(10)

           customer_city customer_state        customer_city_state
0                 franca             SP                 franca, SP
1  sao bernardo do campo             SP  sao bernardo do campo, SP
2              sao paulo             SP              sao paulo, SP
3        mogi das cruzes             SP        mogi das cruzes, SP
4               campinas             SP               campinas, SP
5         jaragua do sul             SC         jaragua do sul, SC
6              sao paulo             SP              sao paulo, SP
7                timoteo             MG                timoteo, MG
8               curitiba             PR               curitiba, PR
9         belo horizonte             MG         belo horizonte, MG

In [4]:
customers["customer_city_state"].describe()

count             99441
unique             4310
top       sao paulo, SP
freq              15540
Name: customer_city_state, dtype: object

In [5]:
customers["customer_city_state"].isnull().sum()

0

In [25]:
customers.to_csv('../Output/customers_features.csv', index = False)